Displayed the suite name of the failed test case.
mint-lang/mint pull request #436
Opened 2021-05-23 11:09 UTC by gdotdesign

Resolves #433

2021-05-23 13:11 UTC, Sija requested changes

2021-05-23 13:11 UTC, Sija commented on src/test_runner.cr
> +        terminal.puts "      |> #{failure.result}".colorize(:red)
I'd group it failures by the suit name so we won't clutter the output with duplicates.

2021-05-23 15:38 UTC, Sija commented on src/test_runner.cr
>        end
I'd do sth like below:

```cr
      @failed.group_by(&.suite) do |suite, failures|
        terminal.puts (suite.presence || "N/A").indent(4).colorize(:red)
        failures.each do |failure|
          terminal.puts "- #{failure.name}".indent(4).colorize(:red)
          terminal.puts "|> #{failure.result}".indent(6).colorize(:red)
        end
      end
```

2021-05-23 16:14 UTC, Sija requested changes

2021-05-23 16:14 UTC, Sija commented on src/test_runner.cr
> +          terminal.puts suite.indent(4).colorize(:red)
This needs to account for empty `suite`:

```suggestion
          terminal.puts (suite.presence || "N/A").indent(4).colorize(:red)
```

2021-05-23 23:22 UTC, Sija commented
@gdotdesign I've pushed some suggested changes:

![image](https://user-images.githubusercontent.com/988/119279754-0ac2fb00-bc2e-11eb-8d2a-a744cfe5cb00.png)

2021-05-24 04:30 UTC, merged

2021-05-24 04:30 UTC, gdotdesign commented
It's fine :slightly_smiling_face: