Extra build mode flags: `--skip-manifest`, `--inline`, and `--watch`
mint-lang/mint pull request #676
Opened 2023-09-25 04:59 UTC by farism

Adds three flags to `mint build` command:

`--skip-manifest` which will skip generating the web manifest file and reference in html.
`--inline` which will inline the JS and CSS into html, resulting in one single file for entire SPA.
`--watch` mode which will write files on changes.

2023-09-25 05:10 UTC, gdotdesign requested changes

2023-09-25 05:10 UTC, gdotdesign commented on src/builder.cr
> +      if !inline
I think it's better to group all `!inline` conditions into an outer `if`.

2023-09-25 09:17 UTC, Sija requested changes

2023-09-25 22:11 UTC, farism commented
Thanks for the review, made requested changes.

2023-09-26 03:27 UTC, gdotdesign approved these changes

2023-09-26 19:52 UTC, Sija approved these changes

2023-09-26 19:52 UTC, merged