Allow referencing assets from the root of the project.
mint-lang/mint pull request #707
Opened 2024-11-18 16:12 UTC by gdotdesign

Currently, assets an only be referenced relative to the file which references them. As per the issue, if there is a file deep in the source directory, referencing a file in the project root requires a lot of `../`.

The PR makes it so that the root path `/` is the project root directory which have the `mint.json` file.

Resolves #459

2024-11-19 22:48 UTC, Sija requested changes

2024-11-19 22:48 UTC, Sija commented on src/ext/file.cr
> +    return path unless directory = File.find_in_ancestors(path, "mint.json")
```suggestion
    return path unless directory = File.find_in_ancestors(path, name)
```

2024-11-20 08:07 UTC, gdotdesign commented on spec/compilers_spec.cr
> +        ast = Mint::Parser.parse(sample, File.dirname(__FILE__) + file.lchop("./spec"))
`File.dirname(__FILE__)` is the `spec` directory, so we need to remove that from the test file.

2024-11-20 11:09 UTC, Sija commented on spec/compilers_spec.cr
> +        ast = Mint::Parser.parse(sample, File.dirname(__FILE__) + file.lchop("./spec"))
And what's wrong with that?

2024-11-20 14:55 UTC, Sija commented on spec/compilers_spec.cr
> +        ast = Mint::Parser.parse(sample, File.dirname(__FILE__) + file.lchop("./spec"))
Isn't because you've added a `mint.json` file to the `spec/` folder?

2024-11-20 15:22 UTC, gdotdesign commented on spec/compilers_spec.cr
> +        ast = Mint::Parser.parse(sample, File.dirname(__FILE__) + file.lchop("./spec"))
Yes, the spec folder becomes the root folder `/` for the tests. So for example `/fixtures/data.txt` is reachable so as `../../fixtures/data.txt` from `spec/compilers/directives/inline` test.

2024-11-20 15:43 UTC, Sija commented on spec/compilers_spec.cr
> +        ast = Mint::Parser.parse(sample, File.dirname(__FILE__) + file.lchop("./spec"))
And why don't you reference the files from the root folder instead? Unless I'm mistaken this way it wouldn't need any hacks.

2024-11-20 15:48 UTC, gdotdesign commented on spec/compilers_spec.cr
> +        ast = Mint::Parser.parse(sample, File.dirname(__FILE__) + file.lchop("./spec"))
I don't follow. We would still need to chop `./spec` off. It doesn't matter if it's absolute or relative. And we still need to find the closest `mint.json` to figure out the root folder.

2024-11-20 19:00 UTC, Sija commented on spec/compilers_spec.cr
> +        ast = Mint::Parser.parse(sample, File.dirname(__FILE__) + file.lchop("./spec"))
Perhaps I don't fully grok the situation. I'm gonna approve it and come back to it later, once I familiarize myself with the recent changes - and there's a lot of 'em 😅

2024-11-20 19:00 UTC, Sija approved these changes

2024-11-21 06:10 UTC, merged